# 01 Dataset Setup

This notebook builds the `Lang` pilot dataset directly from the local `Defects4J` checkout in this folder.

## What it produces

- `data/lang_bug_metadata.csv`
- `data/lang_test_instances.csv`

## Important note

For the lightweight pilot, the unit is a **test class** rather than an individual JUnit test method, because `Defects4J` gives `relevant_tests` at the class level.

In [1]:
from pathlib import Path
import pandas as pd

from d4j_lang_utils import PROJECT_ROOT, load_pilot_bug_ids, build_bug_metadata, build_test_instances

DATA_DIR = PROJECT_ROOT / 'data'
DATA_DIR.mkdir(exist_ok=True)

pilot_bug_ids = load_pilot_bug_ids()
pilot_bug_ids

[1, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [2]:
bug_metadata = build_bug_metadata(pilot_bug_ids)
bug_metadata[['bug_id', 'revision_buggy', 'revision_fixed', 'src_patch_total_changed', 'src_patch_total_files']]

,bug_id,revision_buggy,revision_fixed,src_patch_total_changed,src_patch_total_files
0,1,396afc3e4693cfee182efe582455f2d97058c068,d1a45e9738de5b3e299bb51e987565dcce55fee6,13,1
1,3,64cfee77e333d0c31a0fde0abe6dac3d97b0f078,8a1042959df80c06dbfa83896594caa8e20ff9d6,4,1
2,4,cd91a4f2cd0ced1178e8fd1f49229196eb88094c,0cdc976684efcf478397b68c1d54cefc87bb92c9,8,1
3,5,bc255ccf5c239666ab54e5a31720d3f482ae78eb,4d46f014fb8ee44386feb5fec52509f35d0e36ea,21,1
4,6,f5a83bb90cf7b318ac72823e6b99d01d060abe41,52bcd9b8e82d4d1d287b0d75df1e161aff8c65ab,2,1
5,7,a7b467a74cbe1160d676dc070a19d19764e132a3,350cf8c2da08ccde6b4d71b19bb3df97256ea368,6,1
6,8,cfab1e4fa19755d65de7b81206d86f9e98622d8e,04babff3798680e012646988841bcc710a9e3c54,3,1
7,9,ad72b9f2bf37bd61af18bde67c1622d90a5d8766,65a6458eaa2e1f88278e4bb5753a68bd825e3a80,3,1
8,10,192b1e1b6b96da05cb000b2c89b71467cbfaf245,ad72b9f2bf37bd61af18bde67c1622d90a5d8766,9,1
9,11,27bcbcc728434ffb2c45e81c0e75e6a3d6da3441,4a65cb8da23d6667ac6f91775309b4da9b315d95,4,1

In [3]:
test_instances = build_test_instances(bug_metadata)
test_instances.head(10)

,project_id,bug_id,revision_buggy,revision_fixed,test_id,is_triggering,associated_class_count,associated_classes,associated_changed_lines,associated_hunks,class_affinity_scores,best_affinity
0,Lang,1,396afc3e4693cfee182efe582455f2d97058c068,d1a45e9738de5b3e299bb51e987565dcce55fee6,org.apache.commons.lang3.BooleanUtilsTest,0,1,org.apache.commons.lang3.math.NumberUtils,13,1,org.apache.commons.lang3.math.NumberUtils=0.6087,0.6087
1,Lang,1,396afc3e4693cfee182efe582455f2d97058c068,d1a45e9738de5b3e299bb51e987565dcce55fee6,org.apache.commons.lang3.math.NumberUtilsTest,1,1,org.apache.commons.lang3.math.NumberUtils,13,1,org.apache.commons.lang3.math.NumberUtils=1.0000,1.0000
2,Lang,1,396afc3e4693cfee182efe582455f2d97058c068,d1a45e9738de5b3e299bb51e987565dcce55fee6,org.apache.commons.lang3.reflect.ConstructorUt...,0,1,org.apache.commons.lang3.math.NumberUtils,13,1,org.apache.commons.lang3.math.NumberUtils=0.2500,0.2500
3,Lang,1,396afc3e4693cfee182efe582455f2d97058c068,d1a45e9738de5b3e299bb51e987565dcce55fee6,org.apache.commons.lang3.reflect.MethodUtilsTest,0,1,org.apache.commons.lang3.math.NumberUtils,13,1,org.apache.commons.lang3.math.NumberUtils=0.6364,0.6364
4,Lang,3,64cfee77e333d0c31a0fde0abe6dac3d97b0f078,8a1042959df80c06dbfa83896594caa8e20ff9d6,org.apache.commons.lang3.BooleanUtilsTest,0,1,org.apache.commons.lang3.math.NumberUtils,4,1,org.apache.commons.lang3.math.NumberUtils=0.6087,0.6087
5,Lang,3,64cfee77e333d0c31a0fde0abe6dac3d97b0f078,8a1042959df80c06dbfa83896594caa8e20ff9d6,org.apache.commons.lang3.math.NumberUtilsTest,1,1,org.apache.commons.lang3.math.NumberUtils,4,1,org.apache.commons.lang3.math.NumberUtils=1.0000,1.0000
6,Lang,3,64cfee77e333d0c31a0fde0abe6dac3d97b0f078,8a1042959df80c06dbfa83896594caa8e20ff9d6,org.apache.commons.lang3.reflect.ConstructorUt...,0,1,org.apache.commons.lang3.math.NumberUtils,4,1,org.apache.commons.lang3.math.NumberUtils=0.2500,0.2500
7,Lang,3,64cfee77e333d0c31a0fde0abe6dac3d97b0f078,8a1042959df80c06dbfa83896594caa8e20ff9d6,org.apache.commons.lang3.reflect.MethodUtilsTest,0,1,org.apache.commons.lang3.math.NumberUtils,4,1,org.apache.commons.lang3.math.NumberUtils=0.6364,0.6364
8,Lang,4,cd91a4f2cd0ced1178e8fd1f49229196eb88094c,0cdc976684efcf478397b68c1d54cefc87bb92c9,org.apache.commons.lang3.StringEscapeUtilsTest,0,1,org.apache.commons.lang3.text.translate.Lookup...,8,3,org.apache.commons.lang3.text.translate.Lookup...,0.2500
9,Lang,4,cd91a4f2cd0ced1178e8fd1f49229196eb88094c,0cdc976684efcf478397b68c1d54cefc87bb92c9,org.apache.commons.lang3.StringUtilsTest,0,1,org.apache.commons.lang3.text.translate.Lookup...,8,3,org.apache.commons.lang3.text.translate.Lookup...,0.2500

In [4]:
bug_metadata.to_csv(DATA_DIR / 'lang_bug_metadata.csv', index=False)
test_instances.to_csv(DATA_DIR / 'lang_test_instances.csv', index=False)

print(f'Saved {len(bug_metadata)} bug rows')
print(f'Saved {len(test_instances)} test-instance rows')

Saved 10 bug rows
Saved 51 test-instance rows

In [5]:
validation = pd.DataFrame(
    {
        'bug_id': sorted(test_instances['bug_id'].unique()),
        'num_tests': test_instances.groupby('bug_id')['test_id'].size().sort_index().tolist(),
        'num_triggering_classes': test_instances.groupby('bug_id')['is_triggering'].sum().sort_index().tolist(),
    }
)
validation

   bug_id  num_tests  num_triggering_classes
0       1          4                       1
1       3          4                       1
2       4          4                       1
3       5          1                       1
4       6          9                       1
5       7          4                       1
6       8          8                       2
7       9          8                       2
8      10          8                       2
9      11          1                       1